# Generated by Django 3.2.25 on 2024-11-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0002_auto_20241116_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips_pics/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
