# Generated by Django 5.1.3 on 2024-11-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0005_alter_childpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcategory',
            name='trip',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trek.tripcategory'),
        ),
    ]
