# Generated by Django 5.1.3 on 2024-11-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0007_alter_trip_trip_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_category',
        ),
        migrations.AddField(
            model_name='tripcategory',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_category', to='trek.trip'),
            preserve_default=False,
        ),
    ]
