# Generated by Django 5.1.3 on 2024-11-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0010_remove_trip_image_remove_trip_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
