# Generated by Django 5.1.3 on 2024-11-23 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0011_trip_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
