# Generated by Django 5.1.3 on 2024-12-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0013_tripbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_images/')),
                ('video', models.FileField(upload_to='trips_vedios/')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trek.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
    ]
