# Generated by Django 5.1.3 on 2024-12-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0014_tripmedia_delete_tripimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_images/'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trek.trip'),
        ),
        migrations.AlterField(
            model_name='tripmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='trips_videos/'),
        ),
    ]
