# Generated by Django 5.1.3 on 2024-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0015_alter_tripmedia_image_alter_tripmedia_trip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
