# Generated by Django 5.1.3 on 2024-12-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0016_trip_trip_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_media',
        ),
    ]
