# Generated by Django 5.1.3 on 2024-12-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0017_remove_trip_trip_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='trips/cover_img'),
        ),
    ]
