# Generated by Django 5.1.3 on 2024-12-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0018_trip_cover_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
