# Generated by Django 5.1.3 on 2024-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0022_blogmedia_delete_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
