# Generated by Django 5.1.3 on 2024-12-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0023_blog_blog_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmedia',
            name='blog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trek.blogmedia'),
        ),
    ]
