# Generated by Django 5.1.3 on 2024-12-10 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0024_remove_blogmedia_blog_alter_blog_blog_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_media',
        ),
        migrations.AddField(
            model_name='blogmedia',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='trek.blog'),
            preserve_default=False,
        ),
    ]
