# Generated by Django 5.1.3 on 2024-12-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0027_remove_language_guide_alter_guide_language_spoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='language_spoken',
        ),
        migrations.AddField(
            model_name='guide',
            name='language_spoken',
            field=models.ManyToManyField(related_name='language', to='trek.language'),
        ),
    ]
