# Generated by Django 5.1.3 on 2024-12-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0028_remove_guide_language_spoken_guide_language_spoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
