# Generated by Django 5.1.3 on 2024-12-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0031_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='add_to_cart',
        ),
    ]
