# Generated by Django 5.1.3 on 2024-12-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0035_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='distance',
            field=models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=5),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='flight_hours',
            field=models.DecimalField(decimal_places=2, help_text='Flight hours if applicable', max_digits=5),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='highest_altitude',
            field=models.DecimalField(decimal_places=2, help_text='Maximum altitude in meters', max_digits=7),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trek_duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5),
        ),
    ]
