# Generated by Django 5.1.3 on 2024-12-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0036_alter_itinerary_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='flight_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flight hours if applicable', max_digits=5, null=True),
        ),
    ]
