# Generated by Django 5.1.3 on 2025-01-03 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0037_alter_itinerary_flight_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('emergency_contacts', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('participants', models.PositiveBigIntegerField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('others_information', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trek.country')),
            ],
        ),
    ]
