# Generated by Django 5.1.3 on 2025-01-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0038_country_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
