# Generated by Django 5.1.3 on 2025-01-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0039_alter_booking_country_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trips',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trek.trip'),
            preserve_default=False,
        ),
    ]
