# Generated by Django 5.1.3 on 2025-01-07 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0040_booking_trips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('emergency_contacts', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('participants', models.PositiveBigIntegerField()),
                ('country', models.CharField(max_length=100)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('others_information', models.TextField()),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trek.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TripBooking',
        ),
    ]
