# Generated by Django 5.1.3 on 2025-01-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0041_tripsbooking_delete_tripbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
