# Generated by Django 5.1.3 on 2025-01-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0042_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripsBooking',
        ),
    ]
