# Generated by Django 5.1.3 on 2025-01-20 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0043_delete_tripsbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_start_date', models.DateField()),
                ('full_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_number', models.CharField(max_length=15)),
                ('flight_arrival_date', models.DateField()),
                ('flight_departure_date', models.DateField()),
                ('others_informations', models.TextField(blank=True, null=True)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('trips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trek.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booked_on'],
                'unique_together': {('trips', 'user', 'trip_start_date')},
            },
        ),
    ]
