# Generated by Django 5.1.3 on 2025-01-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0045_trips_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_review',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trek.trip'),
        ),
    ]
