# Generated by Django 5.1.3 on 2025-01-30 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0047_alter_trip_end_date_alter_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_review',
            name='review',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
